Algoritmo "Quadrados dos números"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor(a)    : Bruno Carlso Soares
// Data atual  : 04/04/2024
var
   num:inteiro
   qad:inteiro
inicio
   para num de 15 ate 200 passo 1 faca
        qad <- num*num
        escreval(qad)
   fimpara
fimalgoritmo